package org.akanework.symphonica

const val LOCK_AUDIO_FOCUS_INTERVAL: Long = 50
const val MAX_ALBUM_LIBRARY_LAYOUT = 2
const val DRAWER_ANIMATION_DURATION: Long = 400
const val FULL_PLAYER_FADE_ANIMATION_DURATION: Long = 200
const val PERMISSION_REQUEST_CODE = 123
const val SLIDER_UPDATE_INTERVAL: Long = 500
const val SHEET_OFFSET_MULTIPLE: Float = 2f
const val PLAYER_SLIDER_VALUE_MULTIPLE = 1000
const val MILLISECOND = 1000
const val HOUR_IN_MINUTES = 60
const val FORMAT_ZERO_APPEND = 10
const val PAGE_TRANSITION_DURATION: Long = 500

const val OPTION_HOME = 0
const val OPTION_LIBRARY = 1
const val OPTION_SETTINGS = 2

const val TAB_LIST = 0
const val TAB_ALBUM = 1